# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2860aa223ef14790ab4e4f8bb8eea2b337f2cd5a36aac69a35a2e4d93ed50cb869674885be001c40b95a3fa58923cbaaba3a98cfc0e5e1dc78017ccb68d6441a

test:
  secret_key_base: 589de8e0dbdcf233108ed0cf03e3c3202ac142a7659c1c8429b73dbe48b6d9b1a2f9edbdf6c2a57e08ec41ca344270a70220e7efca6da5e36675d9015f7cb94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
